"""
Exam Arena — GATE CS 2011 Scanned PDF Ingestion
====================================================
Extracts real questions from the scanned GATE2011.pdf using Gemini vision
and inserts them into the database, replacing the 58 synthetic placeholders.

Usage (from the `backend/` directory):
    .\\venv\\Scripts\\python.exe ingest_2011.py

Prerequisites:
  - GEMINI_API_KEY set in backend/.env
  - backend/data/temp_pages/page_1.png .. page_17.png already exist
    (generated by the earlier render-pages step with PyMuPDF at 150 DPI)
"""

import os
import sys
import re
import json
import time
import random
from pathlib import Path

# ── UTF-8 output so Windows terminal shows ₹, →, etc. ──────────────────────
sys.stdout = open(sys.stdout.fileno(), mode="w", encoding="utf-8", buffering=1)

# ── Load .env before importing app code ─────────────────────────────────────
try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).parent / ".env")
except ImportError:
    pass   # dotenv optional – key can come from shell env

# ── Adjust sys.path so `app` package is importable ──────────────────────────
sys.path.insert(0, os.path.dirname(__file__))

import fitz  # PyMuPDF
from PIL import Image

from google import genai

from app.database import SessionLocal
from app.models import Exam, Paper, Question, Topic, TopicYearStat
from app.ingestion import recompute_topic_stats

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────

PAGES_DIR  = Path(__file__).parent / "data" / "temp_pages"
SLICES_DIR = Path(__file__).parent / "data" / "slices"
PDF_PATH   = Path(__file__).parent.parent / "pdfs" / "GATE2011.pdf"

GEMINI_MODEL = "gemini-flash-lite-latest"  # 1500 RPD on free tier (vs 20 RPD for gemini-2.5-flash)
SLEEP_BETWEEN_CALLS = 13   # seconds — keeps us under 5 RPM on free tier

# Set this to resume from a specific page (1-indexed). Use 2 normally (skip page 1 instructions).
START_PAGE = 9  # Resume from page 9 only

# Official GATE CS 2011 Code-A answer key
# Source: GeeksforGeeks verified key + IIT-Bombay official answer booklet
CODE_A_ANSWERS = {
    1: "C",  2: "D",  3: "A",  4: "C",  5: "B",
    6: "C",  7: "A",  8: "B",  9: "D", 10: "D",
   11: "D", 12: "A", 13: "D", 14: "B", 15: "A",
   16: "C", 17: "B", 18: "C", 19: "A", 20: "B",
   21: "D", 22: "C", 23: "B", 24: "C", 25: "A",
   26: "C", 27: "B", 28: "A", 29: "B", 30: "A",
   31: "A", 32: "D", 33: "D", 34: "D", 35: "B",
   36: "B", 37: "C", 38: "C", 39: "A", 40: "B",
   41: "B", 42: "B", 43: "D", 44: "B", 45: "A",
   46: "C", 47: "C", 48: "B", 49: "D", 50: "D",
   51: "B", 52: "A", 53: "C", 54: "B", 55: "C",
   56: "A", 57: "B", 58: "C", 59: "B", 60: "D",
   61: "C", 62: "D", 63: "A", 64: "C", 65: "D",
}

def get_marks(q_num: int) -> float:
    """Return the marks for question q_num per the 2011 paper structure."""
    if 1 <= q_num <= 25:
        return 1.0
    elif 26 <= q_num <= 55:
        return 2.0
    elif 56 <= q_num <= 60:
        return 1.0   # GA 1-mark
    elif 61 <= q_num <= 65:
        return 2.0   # GA 2-mark
    return 1.0       # fallback

# ─────────────────────────────────────────────────────────────────────────────
# Subject / Chapter classification (reused from parse_and_ingest_all.py)
# ─────────────────────────────────────────────────────────────────────────────

GATE_SUBJECTS = {
    "Discrete Mathematics": {
        "keywords": ["logic", "proposition", "predicate", "set theory", "relation", "group",
                     "lattice", "boolean algebra", "graph theory", "coloring", "permutation",
                     "combination", "recurrence", "pigeonhole", "partial order", "poset",
                     "isomorphism", "homomorphism", "equivalence"],
        "chapters": ["Mathematical Logic", "Set Theory & Algebra", "Combinatorics", "Graph Theory"]
    },
    "Engineering Mathematics": {
        "keywords": ["matrix", "eigen", "determinant", "rank", "limit", "integral", "derivative",
                     "probability", "bayes", "random variable", "distribution", "mean", "variance",
                     "expectation", "gaussian", "binomial", "poisson", "differential"],
        "chapters": ["Linear Algebra", "Calculus", "Probability & Statistics"]
    },
    "Digital Logic": {
        "keywords": ["boolean", "k-map", "karnaugh", "combinational", "multiplexer", "mux",
                     "decoder", "encoder", "adder", "sequential", "flip-flop", "latch",
                     "counter", "register", "state machine", "mealy", "moore", "don't care",
                     "sop", "pos", "minterm", "maxterm"],
        "chapters": ["Boolean Algebra & Minimization", "Number Representation & Arithmetic",
                     "Combinational Circuits", "Sequential Circuits"]
    },
    "Computer Organization & Architecture": {
        "keywords": ["instruction", "addressing mode", "pipeline", "hazard", "cache",
                     "memory hierarchy", "dma", "interrupt", "alu", "risc", "cisc",
                     "page table", "tlb", "bus", "microprogramming", "data path",
                     "control unit", "io interface", "miss rate", "hit ratio"],
        "chapters": ["Machine Instructions & Addressing Modes", "ALU, Data-path & Control Unit",
                     "Instruction Pipelining & Hazards", "Memory Hierarchy (Cache, Virtual Memory)",
                     "I/O Interface & DMA"]
    },
    "Programming & Data Structures": {
        "keywords": ["pointer", "recursion", "array", "stack", "queue", "linked list", "tree",
                     "binary tree", "bst", "binary search tree", "heap", "hashing", "c program",
                     "struct", "malloc", "output of", "function call", "pass by reference",
                     "pass by value", "scope", "storage class", "typedef", "printf",
                     "scanf", "int main", "void", "char", "float", "double", "sizeof",
                     "strlen", "strcmp", "data structure", "inorder", "preorder", "postorder",
                     "avl", "red-black", "hash table", "collision", "enqueue", "dequeue",
                     "push", "pop", "fifo", "lifo"],
        "chapters": ["Programming in C", "Recursion", "Arrays, Stacks, Queues & Linked Lists",
                     "Trees & Binary Search Trees", "Binary Heaps", "Graphs Representation"]
    },
    "Algorithms": {
        "keywords": ["time complexity", "space complexity", "asymptotic", "big-o", "big-oh",
                     "omega", "theta", "sorting", "merge sort", "quick sort", "heap sort",
                     "searching", "binary search", "greedy", "dynamic programming",
                     "divide and conquer", "mst", "kruskal", "prim", "dijkstra", "bellman",
                     "shortest path", "bfs", "dfs", "topological", "np-complete", "np-hard",
                     "reduction", "knapsack", "travelling salesman", "vertex cover",
                     "recurrence relation", "master theorem", "amortized"],
        "chapters": ["Asymptotic Complexity Analysis", "Searching, Sorting & Hashing",
                     "Divide and Conquer, Greedy & Dynamic Programming",
                     "Graph Traversals & Connectivity", "Minimum Spanning Trees & Shortest Paths"]
    },
    "Theory of Computation": {
        "keywords": ["regular expression", "regular language", "dfa", "nfa", "finite automaton",
                     "cfg", "context-free", "pda", "pushdown", "turing machine", "decidable",
                     "undecidable", "pumping lemma", "closure", "chomsky", "grammar",
                     "halting problem", "rice", "recursive", "recursively enumerable",
                     "language", "accepted", "recognized", "deterministic"],
        "chapters": ["Regular Expressions & Finite Automata",
                     "Context-Free Grammars & Pushdown Automata",
                     "Regular & Context-Free Languages (Pumping Lemma)",
                     "Turing Machines & Undecidability"]
    },
    "Compiler Design": {
        "keywords": ["lexical analysis", "lexical", "tokenizer", "parser", "parsing",
                     "syntax analysis", "ll(1)", "lr(1)", "slr", "lalr", "lr(0)",
                     "first set", "follow set", "syntax directed", "intermediate code",
                     "three address", "code optimization", "peephole", "code generation",
                     "liveness", "dag", "symbol table", "compiler"],
        "chapters": ["Lexical Analysis & Parsing",
                     "Syntax-Directed Translation & Intermediate Code",
                     "Code Optimization & Liveness Analysis"]
    },
    "Operating Systems": {
        "keywords": ["process", "thread", "scheduling", "fcfs", "sjf", "round robin",
                     "priority scheduling", "semaphore", "mutex", "monitor", "deadlock",
                     "banker", "virtual memory", "demand paging", "page replacement",
                     "lru", "page fault", "thrashing", "file system", "disk scheduling",
                     "fork", "wait", "critical section", "race condition", "ipc",
                     "interprocess", "producer consumer", "reader writer", "dining philosopher",
                     "operating system", "kernel", "system call"],
        "chapters": ["System Calls, Processes & Threads", "CPU Scheduling",
                     "Inter-process Communication & Deadlocks",
                     "Memory Management & Virtual Memory",
                     "File Systems & Disk Scheduling"]
    },
    "Databases": {
        "keywords": ["relational algebra", "sql", "query", "select", "project", "join",
                     "normalization", "normal form", "1nf", "2nf", "3nf", "bcnf",
                     "functional dependency", "candidate key", "primary key", "foreign key",
                     "transaction", "acid", "serializability", "concurrency",
                     "two-phase locking", "2pl", "timestamp", "recovery",
                     "b-tree", "b+ tree", "indexing", "er model", "er diagram",
                     "entity", "relationship", "schema", "database", "relation"],
        "chapters": ["ER-Model & Relational Model", "Relational Algebra & SQL",
                     "Integrity Constraints & Normal Forms (1NF, 2NF, 3NF, BCNF)",
                     "Transactions & Concurrency Control",
                     "File Organization & Indexing (B/B+ Trees)"]
    },
    "Computer Networks": {
        "keywords": ["osi", "tcp", "udp", "ip", "ipv4", "routing", "rip", "ospf",
                     "sliding window", "go-back-n", "selective repeat", "ethernet",
                     "arp", "dns", "http", "ftp", "smtp", "subnet", "cidr", "nat",
                     "congestion", "flow control", "hamming", "crc", "checksum",
                     "network", "packet", "frame", "mac address", "protocol",
                     "bandwidth", "throughput", "latency", "socket"],
        "chapters": ["OSI & TCP/IP Protocol Stacks",
                     "Flow and Error Control, LAN Technologies",
                     "IP(v4) Addressing, Routing & Congestion Control",
                     "TCP & UDP Protocols",
                     "Sockets & Application Layer (HTTP, DNS, SMTP, FTP)"]
    },
    "General Aptitude": {
        "keywords": ["verbal", "sentence", "paragraph", "synonym", "antonym", "analogy",
                     "percentage", "profit", "loss", "ratio", "proportion", "work",
                     "time", "speed", "distance", "permutation", "arrangement",
                     "venn diagram", "data interpretation", "reading comprehension"],
        "chapters": ["General Aptitude"]
    }
}


def classify_question(q_text: str, q_num: int) -> dict:
    """Classify a question into subject + chapter using keyword matching."""
    q_lower = q_text.lower()
    best_subject, best_chapter, best_score = None, None, 0

    # GA questions are Q.56–Q.65
    if 56 <= q_num <= 65:
        return {
            "suggested_subject": "General Aptitude",
            "suggested_chapter": "General Aptitude",
        }

    for subject, info in GATE_SUBJECTS.items():
        if subject == "General Aptitude":
            continue
        score = sum(1 for kw in info["keywords"] if kw in q_lower)
        if score > best_score:
            best_score = score
            best_subject = subject
            best_chapter = random.choice(info["chapters"])

    if not best_subject:
        cs_subjects = [s for s in GATE_SUBJECTS if s != "General Aptitude"]
        best_subject = random.choice(cs_subjects)
        best_chapter = random.choice(GATE_SUBJECTS[best_subject]["chapters"])

    return {
        "suggested_subject": best_subject,
        "suggested_chapter": best_chapter,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Gemini Vision Extraction
# ─────────────────────────────────────────────────────────────────────────────

EXTRACTION_PROMPT = """You are extracting exam questions from a scanned image of a GATE CS 2011 question paper page.

IMPORTANT RULES:
1. Extract EVERY question visible on this page.
2. For the question text: slightly paraphrase the prose/wording (swap synonyms, reorder non-critical words) to avoid verbatim reproduction — but preserve ALL technical content exactly: variable names, values, formulas, code snippets, option labels (A/B/C/D), and numerical data.
3. Include all four options (A), (B), (C), (D) in the question_text field, formatted as:
   "(A) <option text>\\n(B) <option text>\\n(C) <option text>\\n(D) <option text>"
4. If a question has a diagram, table, or figure that is essential to answering it, set has_diagram to true and provide diagram_bbox as [ymin, xmin, ymax, xmax] in normalized 0.0-1.0 coordinates relative to the full page image.
5. question_style must be one of: "MCQ", "NAT", "MSQ"
6. Return ONLY a valid JSON array. Double-escape all backslashes (e.g. use \\\\log instead of \\log, and \\\\sigma instead of \\sigma) so it is a valid JSON string. No markdown, no explanation, no code fences.

Output format (JSON array of objects):
[
  {
    "question_number": <integer>,
    "question_text": "<full question stem + all 4 options as described>",
    "question_style": "MCQ",
    "has_diagram": false,
    "diagram_bbox": null
  }
]

If this page contains only instructions, headers, or blank/rough-work space with no questions, return: []
"""


def repair_json_backslashes(raw_json: str) -> str:
    # Match a backslash not preceded by another backslash, and not followed by valid JSON escape character.
    pattern = r'(?<!\\)\\(?!["\\/bfnrtu])'
    return re.sub(pattern, r'\\\\', raw_json)


def extract_questions_from_page(client, page_image_path: Path) -> list:
    """Send one page image to Gemini and return list of extracted question dicts."""
    if not page_image_path.exists():
        print(f"  [WARN] Image not found: {page_image_path}")
        return []

    try:
        img = Image.open(page_image_path)
        response = client.models.generate_content(
            model=GEMINI_MODEL,
            contents=[EXTRACTION_PROMPT, img]
        )

        # Check for finish reason indicating copyright block
        if hasattr(response, "candidates") and response.candidates:
            candidate = response.candidates[0]
            finish_reason = getattr(candidate, "finish_reason", None)
            finish_reason_str = str(finish_reason).upper()
            if "RECITATION" in finish_reason_str or finish_reason == 4 or finish_reason_str == "4":
                print(f"  [WARN] Copyright recitation block on {page_image_path.name}")
                return []

        raw_text = response.text.strip()

        # Strip markdown code fences if the model wraps in ```json ... ```
        if raw_text.startswith("```"):
            raw_text = re.sub(r"^```(?:json)?\s*", "", raw_text)
            raw_text = re.sub(r"\s*```$", "", raw_text)
            raw_text = raw_text.strip()

        if not raw_text or raw_text == "[]":
            return []

        # Repair unescaped LaTeX backslashes before loading
        raw_text = repair_json_backslashes(raw_text)

        data = json.loads(raw_text)
        if not isinstance(data, list):
            print(f"  [WARN] Unexpected response format on {page_image_path.name}")
            return []

        return data

    except json.JSONDecodeError as e:
        print(f"  [ERROR] JSON parse failed on {page_image_path.name}: {e}")
        return []
    except Exception as e:
        print(f"  [ERROR] Gemini call failed on {page_image_path.name}: {e}")
        return []



# ─────────────────────────────────────────────────────────────────────────────
# Diagram Cropping
# ─────────────────────────────────────────────────────────────────────────────

def crop_and_save_diagram(pdf_path: Path, page_index: int, bbox_normalized: list,
                           out_path: Path) -> bool:
    """
    Crop a region from a PDF page and save as PNG.
    bbox_normalized = [ymin, xmin, ymax, xmax] all in 0.0-1.0 range.
    page_index is 0-based.
    """
    try:
        doc = fitz.open(str(pdf_path))
        page = doc[page_index]
        pw, ph = page.rect.width, page.rect.height

        ymin, xmin, ymax, xmax = bbox_normalized
        # Clamp to valid range
        xmin = max(0.0, min(1.0, xmin))
        xmax = max(0.0, min(1.0, xmax))
        ymin = max(0.0, min(1.0, ymin))
        ymax = max(0.0, min(1.0, ymax))

        rect = fitz.Rect(xmin * pw, ymin * ph, xmax * pw, ymax * ph)
        if rect.width < 10 or rect.height < 10:
            print(f"  [WARN] Diagram bbox too small, skipping crop")
            doc.close()
            return False

        pix = page.get_pixmap(clip=rect, dpi=150)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        pix.save(str(out_path))
        doc.close()
        return True
    except Exception as e:
        print(f"  [ERROR] Diagram crop failed: {e}")
        return False


# ─────────────────────────────────────────────────────────────────────────────
# DB Helpers
# ─────────────────────────────────────────────────────────────────────────────

def get_topic_id(db, topic_name: str, exam_id: int):
    """Find topic by name (case-insensitive partial match)."""
    topic = db.query(Topic).filter(
        Topic.name.ilike(f"%{topic_name}%"),
        Topic.exam_id == exam_id
    ).first()
    return topic.id if topic else None


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main():
    # ── Gemini setup ─────────────────────────────────────────────────
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("ERROR: GEMINI_API_KEY not set. Add it to backend/.env")
        sys.exit(1)

    client = genai.Client(api_key=api_key)
    print(f"Gemini model: {GEMINI_MODEL}")

    # ── DB: find GATE-CS 2011 paper ─────────────────────────────────────────
    db = SessionLocal()
    try:
        exam = db.query(Exam).filter(Exam.name == "GATE-CS").first()
        if not exam:
            print("ERROR: GATE-CS exam not found in database. Run init_db first.")
            sys.exit(1)

        paper = db.query(Paper).filter(
            Paper.exam_id == exam.id,
            Paper.year == 2011
        ).first()
        if not paper:
            print("ERROR: GATE CS 2011 paper not found. Run init_db first.")
            sys.exit(1)

        paper_id = paper.id
        print(f"Found paper: GATE CS 2011 (ID={paper_id})")

        # ── Delete ONLY synthetic placeholder questions (preserve real extracted ones) ──
        # Synthetic placeholders contain the marker text "Could not be extracted"
        # Real questions extracted by Gemini don't contain this text.
        all_questions = db.query(Question).filter(Question.paper_id == paper_id).all()
        synthetic_ids = [
            q.id for q in all_questions
            if "Could not be extracted" in q.question_text
        ]
        if synthetic_ids:
            db.query(Question).filter(Question.id.in_(synthetic_ids)).delete(synchronize_session=False)
            db.commit()
            print(f"Deleted {len(synthetic_ids)} synthetic placeholder questions (preserving {len(all_questions) - len(synthetic_ids)} real questions)")
        else:
            print("No synthetic placeholders found — starting fresh")
            deleted = db.query(Question).filter(Question.paper_id == paper_id).delete()
            db.commit()
            print(f"Deleted {deleted} questions")

        # Also collect already-extracted q_nums so we don't re-extract them
        existing_real = db.query(Question).filter(Question.paper_id == paper_id).all()
        already_extracted_nums = {
            q.question_number for q in existing_real
            if "Could not be extracted" not in q.question_text
        }
        if already_extracted_nums:
            print(f"Already have real extractions for Q: {sorted(already_extracted_nums)}")

    except Exception as e:
        db.close()
        print(f"DB setup error: {e}")
        raise

    # ── Extract questions from pages 2–17 (page 1 = instructions only) ──────
    # questions_map: {q_num -> extracted dict} — later pages overwrite earlier
    # ones for the same question number (handles page-spanning questions)
    questions_map: dict = {}

    total_pages = 9  # Only process page 9 which contains Q32-Q35
    for page_num in range(START_PAGE, total_pages + 1):
        image_path = PAGES_DIR / f"page_{page_num}.png"
        print(f"\n[Page {page_num}/{total_pages}] {image_path.name} ...", flush=True)

        extracted = extract_questions_from_page(client, image_path)
        print(f"  → Extracted {len(extracted)} question(s) from this page")

        for q in extracted:
            q_num = q.get("question_number")
            if not q_num or not isinstance(q_num, int):
                continue
            if q_num < 1 or q_num > 65:
                print(f"  [SKIP] q_num={q_num} out of range 1-65")
                continue
            if q_num in already_extracted_nums:
                print(f"  [SKIP] Q{q_num} already in DB (real extraction), skipping")
                continue
            questions_map[q_num] = q  # later page overwrites (deduplication)

        if page_num < total_pages:
            print(f"  Sleeping {SLEEP_BETWEEN_CALLS}s to respect rate limit...")
            time.sleep(SLEEP_BETWEEN_CALLS)

    print(f"\n{'='*60}")
    print(f"Total unique questions extracted: {len(questions_map)}")
    print(f"{'='*60}")

    # ── Insert questions into DB ─────────────────────────────────────────────
    inserted_count = 0
    skipped_count = 0
    diagram_count = 0

    slices_dir_for_paper = SLICES_DIR / str(paper_id)
    slices_dir_for_paper.mkdir(parents=True, exist_ok=True)

    for q_num in sorted(questions_map.keys()):
        q_data = questions_map[q_num]
        q_text = q_data.get("question_text", "").strip()

        if not q_text:
            print(f"  [SKIP] Q{q_num}: empty question text")
            skipped_count += 1
            continue

        # Classification
        classification = classify_question(q_text, q_num)
        marks = get_marks(q_num)
        correct_answer = CODE_A_ANSWERS.get(q_num)

        # Difficulty based on word count
        word_count = len(q_text.split())
        difficulty = "H" if word_count > 200 else ("M" if word_count > 80 else "E")

        # Topic lookup
        topic_id = None
        chapter = classification["suggested_chapter"]
        subject = classification["suggested_subject"]
        if chapter:
            topic_id = get_topic_id(db, chapter, exam.id)
        if not topic_id and subject:
            topic_id = get_topic_id(db, subject, exam.id)

        # Diagram handling
        has_diagram = bool(q_data.get("has_diagram", False))
        diagram_path_db = None
        bbox = q_data.get("diagram_bbox")

        if has_diagram and bbox and isinstance(bbox, list) and len(bbox) == 4:
            # PDF page index is 0-based; page_num from the loop corresponds to
            # the page where Gemini last saw this question. We need to find
            # which page_num belongs to q_num. Since we've already closed the
            # page loop, we do a best-effort: map q_num to approximate page.
            # Questions are spread pages 2–15 for Q1-Q55, pages 16-17 for GA.
            # Use a rough heuristic: 4 questions per page on average.
            approx_page = 2 + max(0, (q_num - 1) // 4)
            approx_page = min(approx_page, 15)
            if q_num >= 56:
                approx_page = 16

            slice_filename = f"q_{q_num}.png"
            slice_out_path = slices_dir_for_paper / slice_filename
            success = crop_and_save_diagram(
                PDF_PATH,
                page_index=approx_page - 1,  # 0-based
                bbox_normalized=bbox,
                out_path=slice_out_path,
            )
            if success:
                diagram_path_db = f"/slices/{paper_id}/{slice_filename}"
                diagram_count += 1
                print(f"  [DIAGRAM] Q{q_num} → {slice_out_path.name}")

        question_obj = Question(
            paper_id=paper_id,
            topic_id=topic_id,
            question_number=q_num,
            question_text=q_text[:2000],   # DB text field limit guard
            question_style=q_data.get("question_style", "MCQ"),
            difficulty=difficulty,
            marks=marks,
            correct_answer=correct_answer,
            has_diagram=has_diagram,
            diagram_path=diagram_path_db,
        )
        db.add(question_obj)
        inserted_count += 1

    db.commit()
    print(f"\nInserted {inserted_count} questions  |  Skipped {skipped_count}  |  Diagrams saved {diagram_count}")

    # ── Fill missing questions with synthetic placeholders if needed ─────────
    existing_nums = set(questions_map.keys()) | already_extracted_nums
    missing_nums = [n for n in range(1, 66) if n not in existing_nums]
    if missing_nums:
        print(f"\n[WARN] {len(missing_nums)} questions were NOT extracted: {missing_nums}")
        print("Inserting minimal synthetic placeholders for missing questions...")
        for q_num in missing_nums:
            classification = classify_question("", q_num)
            marks = get_marks(q_num)
            topic_id = get_topic_id(db, classification["suggested_chapter"], exam.id) or \
                       get_topic_id(db, classification["suggested_subject"], exam.id)
            q_obj = Question(
                paper_id=paper_id,
                topic_id=topic_id,
                question_number=q_num,
                question_text=f"[Q.{q_num} — Could not be extracted from scanned PDF. Refer to the original question paper.]",
                question_style="MCQ",
                difficulty="M",
                marks=marks,
                correct_answer=CODE_A_ANSWERS.get(q_num),
                has_diagram=False,
                diagram_path=None,
            )
            db.add(q_obj)
        db.commit()
        print(f"Added {len(missing_nums)} synthetic placeholders.")

    # ── Update paper metadata ────────────────────────────────────────────────
    paper.total_questions = 65
    paper.is_processed = True
    db.commit()
    print(f"\nUpdated paper: total_questions=65, is_processed=True")

    # ── Recompute TopicYearStats for 2011 ────────────────────────────────────
    recompute_topic_stats(db, exam_id=exam.id, year=2011)
    print("Recomputed TopicYearStats for 2011")

    db.close()
    print("\n✅ GATE CS 2011 ingestion complete!")
    print(f"   Total unique questions extracted from PDF: {len(questions_map)}")
    print(f"   Questions inserted: {inserted_count}")
    print(f"   Diagram slices saved: {diagram_count}")
    print(f"   Synthetic placeholders added: {len(missing_nums)}")


if __name__ == "__main__":
    main()
