import sqlite3
import os

def patch_db():
    db_path = 'exam_arena.db'
    if not os.path.exists(db_path):
        db_path = 'backend/exam_arena.db'
        
    print(f"Opening database for patching: {db_path}")
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    # 1. ID 922 (2019 Q.1 - Aptitude)
    cursor.execute("""
        UPDATE questions 
        SET question_text = ?, correct_answer = ? 
        WHERE id = 922
    """, (
        "Q.1 \nThe expenditure on the project ______ as follows: equipment Rs.20 lakhs, salaries Rs.12 lakhs, and contingency Rs.3 lakhs.\n\n(A) break down\n(B) break\n(C) breaks down\n(D) breaks",
        "C"
    ))
    
    # 2. ID 932 (2019 Q.1 - Core)
    cursor.execute("""
        UPDATE questions 
        SET question_text = ?, correct_answer = ? 
        WHERE id = 932
    """, (
        "Q.1 \nA certain processor uses a fully associative cache of size 16 kB. The cache block size is 16 bytes. Assume that the main memory is byte addressable and uses a 32-bit address. How many bits are required for the Tag and the Index fields respectively in the addresses generated by the processor?\n\n(A) 24 bits and 0 bits\n(B) 28 bits and 4 bits\n(C) 24 bits and 4 bits\n(D) 28 bits and 0 bits",
        "D"
    ))
    
    # 3. ID 923 (2019 Q.2 - Aptitude)
    cursor.execute("""
        UPDATE questions 
        SET question_text = ?, correct_answer = ? 
        WHERE id = 923
    """, (
        "Q.2 \nThe search engine's business model ___________ around the fulcrum of trust.\n\n(A) revolves\n(B) plays\n(C) sinks\n(D) bursts",
        "A"
    ))
    
    # 4. ID 933 (2019 Q.2 - Core)
    cursor.execute("""
        UPDATE questions 
        SET question_text = ?, correct_answer = ? 
        WHERE id = 933
    """, (
        "Q.2 \nThe chip select logic for a certain DRAM chip in a memory system design is shown below. Assume that the memory system has 16 address lines denoted by A15 to A0. What is the range of addresses (in hexadecimal) of the memory system that can get enabled by the chip select (CS) signal?\n\n(A) C800 to CFFF\n(B) CA00 to CAFF\n(C) C800 to C8FF\n(D) DA00 to DFFF",
        "C"
    ))
    
    # 5. ID 924 (2019 Q.3 - Aptitude)
    cursor.execute("""
        UPDATE questions 
        SET question_text = ?, correct_answer = ? 
        WHERE id = 924
    """, (
        "Q.3 \nTwo cars start at the same time from the same location and go in the same direction. The speed of the first car is 50 km/h and the speed of the second car is 60 km/h. The number of hours it takes for the distance between the two cars to be 20 km is ___.\n\n(A) 1\n(B) 2\n(C) 3\n(D) 6",
        "B"
    ))
    
    # 6. ID 934 (2019 Q.3 - Core)
    cursor.execute("""
        UPDATE questions 
        SET question_text = ?, correct_answer = ? 
        WHERE id = 934
    """, (
        "Q.3 \nWhich one of the following kinds of derivation is used by LR parsers?\n\n(A) Leftmost\n(B) Leftmost in reverse\n(C) Rightmost\n(D) Rightmost in reverse",
        "D"
    ))
    
    # 7. ID 925 (2019 Q.4 - Aptitude)
    cursor.execute("""
        UPDATE questions 
        SET question_text = ?, correct_answer = ? 
        WHERE id = 925
    """, (
        "Q.4 \nTen friends planned to share equally the cost of buying a gift for their teacher. When two of them decided not to contribute, each of the other friends had to pay Rs 150 more. The cost of the gift was Rs. ____.\n\n(A) 3000\n(B) 6000\n(C) 12000\n(D) 18000",
        "B"
    ))
    
    # 8. ID 935 (2019 Q.4 - Core)
    cursor.execute("""
        UPDATE questions 
        SET question_text = ?, correct_answer = ? 
        WHERE id = 935
    """, (
        "Q.4 \nIn 16-bit 2's complement representation, the decimal number -28 is:\n\n(A) 1111 1111 0001 1100\n(B) 0000 0000 1110 0100\n(C) 1111 1111 1110 0100\n(D) 1000 0000 1110 0100",
        "C"
    ))
    
    # 9. ID 926 (2019 Q.5 - Aptitude)
    cursor.execute("""
        UPDATE questions 
        SET question_text = ?, correct_answer = ? 
        WHERE id = 926
    """, (
        "Q.5 \nA court is to a judge as _____________ is to a teacher.\n\n(A) a classroom\n(B) a school\n(C) a student\n(D) a syllabus",
        "B"
    ))
    
    # 10. ID 936 (2019 Q.5 - Core)
    cursor.execute("""
        UPDATE questions 
        SET correct_answer = ? 
        WHERE id = 936
    """, (
        "C",
    ))
    
    conn.commit()
    print("Database patched successfully!")
    
    # Verify updates
    cursor.execute("SELECT id, correct_answer FROM questions WHERE id IN (922, 932, 923, 933, 924, 934, 925, 935, 926, 936)")
    print("Verification result:")
    for q_id, ans in cursor.fetchall():
        print(f"ID {q_id}: Correct Answer = {ans}")
        
    conn.close()

if __name__ == '__main__':
    patch_db()
